# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
    groups:
      gradle:
        patterns:
          - "*"

  # - package-ecosystem: "pip"
  #   directory: "/components/pre-processing"
  #   schedule:
  #     interval: "weekly"
  #   commit-message:
  #     prefix: ⬆
  #   groups:
  #     production-dependencies:
  #       dependency-type: production
  #     development-dependencies:
  #       dependency-type: development
