repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.4
          - prettier-plugin-java@2.5.0
        types_or:
          - "java"

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: [--profile, black, --skip, alembic]

  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0" # pick a git hash / tag to point to
    hooks:
      - id: flake8
        name: flake8
        args: [--max-line-length=120, "--ignore=W291,W503"]
