/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pfe_broker.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MarketDataRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5187035315923793626L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MarketDataRequest\",\"namespace\":\"pfe_broker.avro\",\"fields\":[{\"name\":\"username\",\"type\":\"string\"},{\"name\":\"symbols\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"depth\",\"type\":\"int\"},{\"name\":\"marketDataEntries\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"enum\",\"name\":\"MarketDataEntry\",\"symbols\":[\"LOW\",\"HIGH\",\"OPEN\",\"CLOSE\"]}}},{\"name\":\"marketDataSubscriptionRequest\",\"type\":{\"type\":\"enum\",\"name\":\"MarketDataSubscriptionRequest\",\"symbols\":[\"SNAPSHOT\",\"SUBSCRIBE\",\"UNSUBSCRIBE\"]}},{\"name\":\"requestId\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MarketDataRequest> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MarketDataRequest> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MarketDataRequest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MarketDataRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MarketDataRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MarketDataRequest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MarketDataRequest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MarketDataRequest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MarketDataRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence username;
  private java.util.List<java.lang.CharSequence> symbols;
  private int depth;
  private java.util.List<pfe_broker.avro.MarketDataEntry> marketDataEntries;
  private pfe_broker.avro.MarketDataSubscriptionRequest marketDataSubscriptionRequest;
  private java.lang.CharSequence requestId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MarketDataRequest() {}

  /**
   * All-args constructor.
   * @param username The new value for username
   * @param symbols The new value for symbols
   * @param depth The new value for depth
   * @param marketDataEntries The new value for marketDataEntries
   * @param marketDataSubscriptionRequest The new value for marketDataSubscriptionRequest
   * @param requestId The new value for requestId
   */
  public MarketDataRequest(java.lang.CharSequence username, java.util.List<java.lang.CharSequence> symbols, java.lang.Integer depth, java.util.List<pfe_broker.avro.MarketDataEntry> marketDataEntries, pfe_broker.avro.MarketDataSubscriptionRequest marketDataSubscriptionRequest, java.lang.CharSequence requestId) {
    this.username = username;
    this.symbols = symbols;
    this.depth = depth;
    this.marketDataEntries = marketDataEntries;
    this.marketDataSubscriptionRequest = marketDataSubscriptionRequest;
    this.requestId = requestId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return username;
    case 1: return symbols;
    case 2: return depth;
    case 3: return marketDataEntries;
    case 4: return marketDataSubscriptionRequest;
    case 5: return requestId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: username = (java.lang.CharSequence)value$; break;
    case 1: symbols = (java.util.List<java.lang.CharSequence>)value$; break;
    case 2: depth = (java.lang.Integer)value$; break;
    case 3: marketDataEntries = (java.util.List<pfe_broker.avro.MarketDataEntry>)value$; break;
    case 4: marketDataSubscriptionRequest = (pfe_broker.avro.MarketDataSubscriptionRequest)value$; break;
    case 5: requestId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'username' field.
   * @return The value of the 'username' field.
   */
  public java.lang.CharSequence getUsername() {
    return username;
  }


  /**
   * Sets the value of the 'username' field.
   * @param value the value to set.
   */
  public void setUsername(java.lang.CharSequence value) {
    this.username = value;
  }

  /**
   * Gets the value of the 'symbols' field.
   * @return The value of the 'symbols' field.
   */
  public java.util.List<java.lang.CharSequence> getSymbols() {
    return symbols;
  }


  /**
   * Sets the value of the 'symbols' field.
   * @param value the value to set.
   */
  public void setSymbols(java.util.List<java.lang.CharSequence> value) {
    this.symbols = value;
  }

  /**
   * Gets the value of the 'depth' field.
   * @return The value of the 'depth' field.
   */
  public int getDepth() {
    return depth;
  }


  /**
   * Sets the value of the 'depth' field.
   * @param value the value to set.
   */
  public void setDepth(int value) {
    this.depth = value;
  }

  /**
   * Gets the value of the 'marketDataEntries' field.
   * @return The value of the 'marketDataEntries' field.
   */
  public java.util.List<pfe_broker.avro.MarketDataEntry> getMarketDataEntries() {
    return marketDataEntries;
  }


  /**
   * Sets the value of the 'marketDataEntries' field.
   * @param value the value to set.
   */
  public void setMarketDataEntries(java.util.List<pfe_broker.avro.MarketDataEntry> value) {
    this.marketDataEntries = value;
  }

  /**
   * Gets the value of the 'marketDataSubscriptionRequest' field.
   * @return The value of the 'marketDataSubscriptionRequest' field.
   */
  public pfe_broker.avro.MarketDataSubscriptionRequest getMarketDataSubscriptionRequest() {
    return marketDataSubscriptionRequest;
  }


  /**
   * Sets the value of the 'marketDataSubscriptionRequest' field.
   * @param value the value to set.
   */
  public void setMarketDataSubscriptionRequest(pfe_broker.avro.MarketDataSubscriptionRequest value) {
    this.marketDataSubscriptionRequest = value;
  }

  /**
   * Gets the value of the 'requestId' field.
   * @return The value of the 'requestId' field.
   */
  public java.lang.CharSequence getRequestId() {
    return requestId;
  }


  /**
   * Sets the value of the 'requestId' field.
   * @param value the value to set.
   */
  public void setRequestId(java.lang.CharSequence value) {
    this.requestId = value;
  }

  /**
   * Creates a new MarketDataRequest RecordBuilder.
   * @return A new MarketDataRequest RecordBuilder
   */
  public static pfe_broker.avro.MarketDataRequest.Builder newBuilder() {
    return new pfe_broker.avro.MarketDataRequest.Builder();
  }

  /**
   * Creates a new MarketDataRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MarketDataRequest RecordBuilder
   */
  public static pfe_broker.avro.MarketDataRequest.Builder newBuilder(pfe_broker.avro.MarketDataRequest.Builder other) {
    if (other == null) {
      return new pfe_broker.avro.MarketDataRequest.Builder();
    } else {
      return new pfe_broker.avro.MarketDataRequest.Builder(other);
    }
  }

  /**
   * Creates a new MarketDataRequest RecordBuilder by copying an existing MarketDataRequest instance.
   * @param other The existing instance to copy.
   * @return A new MarketDataRequest RecordBuilder
   */
  public static pfe_broker.avro.MarketDataRequest.Builder newBuilder(pfe_broker.avro.MarketDataRequest other) {
    if (other == null) {
      return new pfe_broker.avro.MarketDataRequest.Builder();
    } else {
      return new pfe_broker.avro.MarketDataRequest.Builder(other);
    }
  }

  /**
   * RecordBuilder for MarketDataRequest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MarketDataRequest>
    implements org.apache.avro.data.RecordBuilder<MarketDataRequest> {

    private java.lang.CharSequence username;
    private java.util.List<java.lang.CharSequence> symbols;
    private int depth;
    private java.util.List<pfe_broker.avro.MarketDataEntry> marketDataEntries;
    private pfe_broker.avro.MarketDataSubscriptionRequest marketDataSubscriptionRequest;
    private java.lang.CharSequence requestId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(pfe_broker.avro.MarketDataRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.username)) {
        this.username = data().deepCopy(fields()[0].schema(), other.username);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.symbols)) {
        this.symbols = data().deepCopy(fields()[1].schema(), other.symbols);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.depth)) {
        this.depth = data().deepCopy(fields()[2].schema(), other.depth);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.marketDataEntries)) {
        this.marketDataEntries = data().deepCopy(fields()[3].schema(), other.marketDataEntries);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.marketDataSubscriptionRequest)) {
        this.marketDataSubscriptionRequest = data().deepCopy(fields()[4].schema(), other.marketDataSubscriptionRequest);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.requestId)) {
        this.requestId = data().deepCopy(fields()[5].schema(), other.requestId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing MarketDataRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(pfe_broker.avro.MarketDataRequest other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.username)) {
        this.username = data().deepCopy(fields()[0].schema(), other.username);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.symbols)) {
        this.symbols = data().deepCopy(fields()[1].schema(), other.symbols);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.depth)) {
        this.depth = data().deepCopy(fields()[2].schema(), other.depth);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.marketDataEntries)) {
        this.marketDataEntries = data().deepCopy(fields()[3].schema(), other.marketDataEntries);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.marketDataSubscriptionRequest)) {
        this.marketDataSubscriptionRequest = data().deepCopy(fields()[4].schema(), other.marketDataSubscriptionRequest);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.requestId)) {
        this.requestId = data().deepCopy(fields()[5].schema(), other.requestId);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'username' field.
      * @return The value.
      */
    public java.lang.CharSequence getUsername() {
      return username;
    }


    /**
      * Sets the value of the 'username' field.
      * @param value The value of 'username'.
      * @return This builder.
      */
    public pfe_broker.avro.MarketDataRequest.Builder setUsername(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.username = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'username' field has been set.
      * @return True if the 'username' field has been set, false otherwise.
      */
    public boolean hasUsername() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'username' field.
      * @return This builder.
      */
    public pfe_broker.avro.MarketDataRequest.Builder clearUsername() {
      username = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'symbols' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getSymbols() {
      return symbols;
    }


    /**
      * Sets the value of the 'symbols' field.
      * @param value The value of 'symbols'.
      * @return This builder.
      */
    public pfe_broker.avro.MarketDataRequest.Builder setSymbols(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.symbols = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'symbols' field has been set.
      * @return True if the 'symbols' field has been set, false otherwise.
      */
    public boolean hasSymbols() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'symbols' field.
      * @return This builder.
      */
    public pfe_broker.avro.MarketDataRequest.Builder clearSymbols() {
      symbols = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'depth' field.
      * @return The value.
      */
    public int getDepth() {
      return depth;
    }


    /**
      * Sets the value of the 'depth' field.
      * @param value The value of 'depth'.
      * @return This builder.
      */
    public pfe_broker.avro.MarketDataRequest.Builder setDepth(int value) {
      validate(fields()[2], value);
      this.depth = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'depth' field has been set.
      * @return True if the 'depth' field has been set, false otherwise.
      */
    public boolean hasDepth() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'depth' field.
      * @return This builder.
      */
    public pfe_broker.avro.MarketDataRequest.Builder clearDepth() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'marketDataEntries' field.
      * @return The value.
      */
    public java.util.List<pfe_broker.avro.MarketDataEntry> getMarketDataEntries() {
      return marketDataEntries;
    }


    /**
      * Sets the value of the 'marketDataEntries' field.
      * @param value The value of 'marketDataEntries'.
      * @return This builder.
      */
    public pfe_broker.avro.MarketDataRequest.Builder setMarketDataEntries(java.util.List<pfe_broker.avro.MarketDataEntry> value) {
      validate(fields()[3], value);
      this.marketDataEntries = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'marketDataEntries' field has been set.
      * @return True if the 'marketDataEntries' field has been set, false otherwise.
      */
    public boolean hasMarketDataEntries() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'marketDataEntries' field.
      * @return This builder.
      */
    public pfe_broker.avro.MarketDataRequest.Builder clearMarketDataEntries() {
      marketDataEntries = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'marketDataSubscriptionRequest' field.
      * @return The value.
      */
    public pfe_broker.avro.MarketDataSubscriptionRequest getMarketDataSubscriptionRequest() {
      return marketDataSubscriptionRequest;
    }


    /**
      * Sets the value of the 'marketDataSubscriptionRequest' field.
      * @param value The value of 'marketDataSubscriptionRequest'.
      * @return This builder.
      */
    public pfe_broker.avro.MarketDataRequest.Builder setMarketDataSubscriptionRequest(pfe_broker.avro.MarketDataSubscriptionRequest value) {
      validate(fields()[4], value);
      this.marketDataSubscriptionRequest = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'marketDataSubscriptionRequest' field has been set.
      * @return True if the 'marketDataSubscriptionRequest' field has been set, false otherwise.
      */
    public boolean hasMarketDataSubscriptionRequest() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'marketDataSubscriptionRequest' field.
      * @return This builder.
      */
    public pfe_broker.avro.MarketDataRequest.Builder clearMarketDataSubscriptionRequest() {
      marketDataSubscriptionRequest = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'requestId' field.
      * @return The value.
      */
    public java.lang.CharSequence getRequestId() {
      return requestId;
    }


    /**
      * Sets the value of the 'requestId' field.
      * @param value The value of 'requestId'.
      * @return This builder.
      */
    public pfe_broker.avro.MarketDataRequest.Builder setRequestId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.requestId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'requestId' field has been set.
      * @return True if the 'requestId' field has been set, false otherwise.
      */
    public boolean hasRequestId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'requestId' field.
      * @return This builder.
      */
    public pfe_broker.avro.MarketDataRequest.Builder clearRequestId() {
      requestId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MarketDataRequest build() {
      try {
        MarketDataRequest record = new MarketDataRequest();
        record.username = fieldSetFlags()[0] ? this.username : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.symbols = fieldSetFlags()[1] ? this.symbols : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[1]);
        record.depth = fieldSetFlags()[2] ? this.depth : (java.lang.Integer) defaultValue(fields()[2]);
        record.marketDataEntries = fieldSetFlags()[3] ? this.marketDataEntries : (java.util.List<pfe_broker.avro.MarketDataEntry>) defaultValue(fields()[3]);
        record.marketDataSubscriptionRequest = fieldSetFlags()[4] ? this.marketDataSubscriptionRequest : (pfe_broker.avro.MarketDataSubscriptionRequest) defaultValue(fields()[4]);
        record.requestId = fieldSetFlags()[5] ? this.requestId : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MarketDataRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<MarketDataRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MarketDataRequest>
    READER$ = (org.apache.avro.io.DatumReader<MarketDataRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.username);

    long size0 = this.symbols.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.symbols) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeInt(this.depth);

    long size1 = this.marketDataEntries.size();
    out.writeArrayStart();
    out.setItemCount(size1);
    long actualSize1 = 0;
    for (pfe_broker.avro.MarketDataEntry e1: this.marketDataEntries) {
      actualSize1++;
      out.startItem();
      out.writeEnum(e1.ordinal());
    }
    out.writeArrayEnd();
    if (actualSize1 != size1)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size1 + ", but element count was " + actualSize1 + ".");

    out.writeEnum(this.marketDataSubscriptionRequest.ordinal());

    out.writeString(this.requestId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.username = in.readString(this.username instanceof Utf8 ? (Utf8)this.username : null);

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.symbols;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("symbols").schema());
        this.symbols = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

      this.depth = in.readInt();

      long size1 = in.readArrayStart();
      java.util.List<pfe_broker.avro.MarketDataEntry> a1 = this.marketDataEntries;
      if (a1 == null) {
        a1 = new SpecificData.Array<pfe_broker.avro.MarketDataEntry>((int)size1, SCHEMA$.getField("marketDataEntries").schema());
        this.marketDataEntries = a1;
      } else a1.clear();
      SpecificData.Array<pfe_broker.avro.MarketDataEntry> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<pfe_broker.avro.MarketDataEntry>)a1 : null);
      for ( ; 0 < size1; size1 = in.arrayNext()) {
        for ( ; size1 != 0; size1--) {
          pfe_broker.avro.MarketDataEntry e1 = (ga1 != null ? ga1.peek() : null);
          e1 = pfe_broker.avro.MarketDataEntry.values()[in.readEnum()];
          a1.add(e1);
        }
      }

      this.marketDataSubscriptionRequest = pfe_broker.avro.MarketDataSubscriptionRequest.values()[in.readEnum()];

      this.requestId = in.readString(this.requestId instanceof Utf8 ? (Utf8)this.requestId : null);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.username = in.readString(this.username instanceof Utf8 ? (Utf8)this.username : null);
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.symbols;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("symbols").schema());
            this.symbols = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        case 2:
          this.depth = in.readInt();
          break;

        case 3:
          long size1 = in.readArrayStart();
          java.util.List<pfe_broker.avro.MarketDataEntry> a1 = this.marketDataEntries;
          if (a1 == null) {
            a1 = new SpecificData.Array<pfe_broker.avro.MarketDataEntry>((int)size1, SCHEMA$.getField("marketDataEntries").schema());
            this.marketDataEntries = a1;
          } else a1.clear();
          SpecificData.Array<pfe_broker.avro.MarketDataEntry> ga1 = (a1 instanceof SpecificData.Array ? (SpecificData.Array<pfe_broker.avro.MarketDataEntry>)a1 : null);
          for ( ; 0 < size1; size1 = in.arrayNext()) {
            for ( ; size1 != 0; size1--) {
              pfe_broker.avro.MarketDataEntry e1 = (ga1 != null ? ga1.peek() : null);
              e1 = pfe_broker.avro.MarketDataEntry.values()[in.readEnum()];
              a1.add(e1);
            }
          }
          break;

        case 4:
          this.marketDataSubscriptionRequest = pfe_broker.avro.MarketDataSubscriptionRequest.values()[in.readEnum()];
          break;

        case 5:
          this.requestId = in.readString(this.requestId instanceof Utf8 ? (Utf8)this.requestId : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










