{
 "title": "KMinion Cluster Dashboard - Prometheus Exporter for Apache Kafka",
 "description": "Cluster wide metrics exported by KMinion",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "highThroughputTopics",
    "query": {
     "query": "query_result(avg by (topic_name) (avg_over_time(kminion_kafka_topic_high_water_mark_sum[${__range_s}s])))"
    }
   },
   {
    "name": "topOffsetCommitters",
    "query": "query_result(topk(5, avg by (group_id) (avg_over_time(kminion_kafka_consumer_group_offset_commits_total[${__range_s}s]))))"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages in/sec",
   "type": "timeseries",
   "description": "Summed delta between High and Low watermark of all partitions in the given topic. Therefore not accurate for compacted topics that contain compacted records.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kminion_kafka_topic_high_water_mark_sum{topic_name!~\"__consumer_offsets|_schemas\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Cluster Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kminion_kafka_cluster_info" }
   ]
  },
  {
   "title": "Brokers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "kminion_kafka_broker_info" }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kminion_kafka_cluster_info" }
   ]
  },
  {
   "title": "Log Dir Size by Broker",
   "type": "timeseries",
   "description": "Log dir size across all log dirs, topics and partitions for a given broker.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (broker_id) (kminion_kafka_broker_log_dir_size_total_bytes)",
     "legendFormat": "Broker {{broker_id}}"
    }
   ]
  },
  {
   "title": "Messages in/sec by topic [Top 15]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(topic_name) (rate(kminion_kafka_topic_high_water_mark_sum{topic_name=~\"$highThroughputTopics\", topic_name!~\"__consumer_offsets|_schemas\"}[$__rate_interval]))",
     "legendFormat": "{{topic_name}}"
    }
   ]
  },
  {
   "title": "Top Offset Committers [Top 5]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(group_id) (rate(kminion_kafka_consumer_group_offset_commits_total{group_id=~\"$highThroughputTopics\"}[$__rate_interval]))",
     "legendFormat": "{{group_id}}"
    }
   ]
  },
  {
   "title": "Offset commits processed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (kubernetes_pod_name) (rate(kminion_exporter_offset_consumer_records_consumed_total[$__rate_interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}