{
 "title": "Market Matcher",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Symbol",
    "query": {
     "query": "label_values(market_matcher_process_order_seconds_count,symbol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Symbols matched",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(symbol) (market_matcher_process_order_seconds_count{symbol=\"$Symbol\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nb matched orders /s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg(rate(market_matcher_process_order_seconds_count{symbol=\"$Symbol\"}[$__rate_interval]))",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Nb matched orders",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "avg by(side) (market_matcher_process_order_seconds_count{symbol=\"$Symbol\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time to match an order",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(side) (market_matcher_process_order_seconds_sum{symbol=\"$Symbol\"}) / avg by(side) (market_matcher_process_order_seconds_count{symbol=\"$Symbol\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected orders",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "market_matcher_rejected_order_total{symbol=\"$Symbol\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}