{
 "title": "Market Data Subscription",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total volume of subscription",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "order_book_market_data_subscription",
     "legendFormat": "{{side}}"
    }
   ]
  },
  {
   "title": "Average time to handle market data request",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(subscriptionRequest) (order_book_market_data_request_seconds_sum) / avg by(subscriptionRequest) (order_book_market_data_request_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Market data request received/s",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(subscriptionRequest) (rate(order_book_market_data_request_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All responses sent",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "order_book_market_data_responses_total",
     "legendFormat": "{{symbol}}"
    },
    {
     "expr": "order_book_rejected_total{symbol=\"$Symbol\"}",
     "legendFormat": "Rejection - {{requestType}}"
    }
   ]
  },
  {
   "title": "Market data request rejected",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(reason) (order_book_market_data_rejected_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}