{
 "title": "Order Book",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Symbol",
    "query": {
     "query": "label_values(order_book_volume_order_book,symbol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total volume of order book",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "order_book_volume_order_book{symbol=\"$Symbol\"}",
     "legendFormat": "{{side}}"
    }
   ]
  },
  {
   "title": "Average time to handle order book request",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(order_book_handle_order_seconds_sum{symbol=\"$Symbol\"}) / avg(order_book_handle_order_seconds_count{symbol=\"$Symbol\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time to match orders",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "order_book_match_orders_seconds_sum{symbol=\"$Symbol\"} / order_book_match_orders_seconds_count{symbol=\"$Symbol\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order book request received/s",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(requestType) (rate(order_book_handle_order_seconds_count{symbol=\"$Symbol\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All responses sent",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "order_book_responses_total{symbol=\"$Symbol\"}",
     "legendFormat": "Response - {{requestType}}"
    },
    {
     "expr": "order_book_rejected_total{symbol=\"$Symbol\"}",
     "legendFormat": "Rejection - {{requestType}}"
    }
   ]
  },
  {
   "title": "Trades fullfilled",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "order_book_trades_total{symbol=\"$Symbol\"}",
     "legendFormat": "Trades"
    }
   ]
  }
 ]
}