{
 "title": "Order stream",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Symbol",
    "query": {
     "query": "label_values(order_stream_check_integrity_seconds_count,symbol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average time to verify MARKET order",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(side) (order_stream_check_integrity_seconds_sum{symbol=\"$Symbol\", type=\"MARKET\"}) / avg by(side) (order_stream_check_integrity_seconds_count{symbol=\"$Symbol\", type=\"MARKET\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time to verify LIMIT order",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(side) (order_stream_check_integrity_seconds_sum{symbol=\"$Symbol\", type=\"LIMIT\"}) / avg by(side) (order_stream_check_integrity_seconds_count{symbol=\"$Symbol\", type=\"LIMIT\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted orders",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "order_stream_accepted_order_total{symbol=\"$Symbol\"}",
     "legendFormat": "{{type}} - {{side}}"
    }
   ]
  },
  {
   "title": "Rejected orders",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(orderRejectReason) (order_stream_rejected_order_total{symbol=\"$Symbol\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}