{
 "title": "Quickfix server",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Users connected",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quickfix_server_users_connected",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages received/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(type) (rate(quickfix_server_messages_received_total[$__rate_interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Messages received",
   "type": "stat",
   "gridPos": { "h": 22, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quickfix_server_messages_received_total",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Messages sent",
   "type": "stat",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(type) (quickfix_server_messages_sent_total)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}