global:
  scrape_interval: "1s"
  scrape_timeout: "1s"
  evaluation_interval: "1s"

scrape_configs:
  - job_name: "market-matcher"
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["host.docker.internal:10001"]

  - job_name: "order-book"
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["host.docker.internal:10002"]

  - job_name: "order-stream"
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["host.docker.internal:10003"]

  - job_name: "quickfix-server"
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["host.docker.internal:10004"]

  - job_name: "trade-stream"
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["host.docker.internal:10005"]

  - job_name: "kminion"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["kminion:8000"]
