datasources:
  default:
    db-type: postgresql
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
---
jpa:
  default:
    properties.hibernate.hbm2ddl.auto: update
    entity-scan.packages: pfe_broker.models.domains
