datasources:
  default:
    db-type: postgresql
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:seak}
---
jpa:
  default:
    properties.hibernate.hbm2ddl.auto: update
    entity-scan.packages: seak.models.domains
