name: CI - Java
on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version:
          - "17"
        project:
          - market-matcher
          - order-book
          - order-stream
          - quickfix-server
          - trade-stream
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
          cache: "gradle"

      - name: Clean gradle cache
        run: ./gradlew clean --no-daemon

      - name: Test Java project
        run: ./gradlew :components:${{ matrix.project }}:test
