name: CI - Python
on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
        project:
          - "components/pre-processing"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Store poetry.lock path
        id: poetry-path
        run: echo "path=./${{ matrix.project }}/poetry.lock" >> $GITHUB_OUTPUT

      - name: Install poetry
        uses: abatilo/actions-poetry@v3

      - name: Define a cache for the virtual environment based on the dependencies lock file for ${{ matrix.project }}
        uses: actions/cache@v3
        with:
          path: ./${{ matrix.project }}/.venv
          key: venv-${{ matrix.project }}-${{ hashFiles(steps.poetry-path.outputs.path) }}

      - name: Install Dependencies
        run: cd ./${{ matrix.project }}; poetry install

      - name: Test
        run: cd ./${{ matrix.project }}; poetry run pytest tests/
