name: CI - Python
on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Set shas
        uses: nrwl/nx-set-shas@v4

      - name: Get main branch
        # Verify the event is a pull request and the base branch is not main
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref != 'main'
        # This line is needed for nx affected to work when CI is running on a PR
        run: git branch --track main origin/main

      - name: Verify formatting
        run: npx nx format:check --exclude='*,!tag:lang:python'

  pre-processing:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Define a cache for the virtual environment based on the dependencies lock file
        uses: actions/cache@v3
        with:
          path: ./components/pre-processing/.venv
          key: venv-pre-processing-${{ hashFiles('./components/pre-processing/poetry.lock') }}

      - name: Install Dependencies
        run: poetry install

      - name: Test
        run: npx nx run-many -t lint,test,build --projects=pre-processing
