name: CI
on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"
      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Set shas
        uses: nrwl/nx-set-shas@v4

      - name: Get main branch
        # Verify the event is a pull request and the base branch is not main
        if: github.event_name == 'pull_request' && github.event.pull_request.base.ref != 'main'
        # This line is needed for nx affected to work when CI is running on a PR
        run: git branch --track main origin/main

      - name: Clean gradle cache
        run: ./gradlew clean --no-daemon

      - name: Verify formatting
        run: npx nx format:check

      - name: Test Java projects
        run: npx nx affected -t build --parallel=3 --exclude='*,!tag:lang:java'

      - name: Test Python projects
        run: npx nx affected -t lint,test,build --parallel=3 --exclude='*,!tag:lang:python'
