name: Labels pull request

on:
  pull_request:
    branches:
      - main

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the current version from gradle.properties
        id: version
        run: |
          echo "version=$(cat gradle.properties | grep version | cut -d= -f2)" >> $GITHUB_OUTPUT

      - name: Get the label to add
        id: get_label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = ["release:patch", "release:minor", "release:major"];
            let last_release = {
                data: {
                    tag_name: "v0.0.0",
                },
            }
            try {
                last_release = await github.repos.getLatestRelease({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                });
            } catch (error) {
                console.log("No release found");
            }
            const last_release_tag = last_release.data.tag_name;
            const last_release_version = last_release_tag.replace("v", "");
            if (last_release_version === process.env.VERSION) {
                core.setFailed("The version has not been bumped");
            } else {
                const last_release_version_split = last_release_version.split(".");
                const current_version_split = process.env.VERSION.split(".");
                if (last_release_version_split[0] !== current_version_split[0]) {
                    core.setOutput("label", labels[2]);
                } else if (last_release_version_split[1] !== current_version_split[1]) {
                    core.setOutput("label", labels[1]);
                } else {
                    core.setOutput("label", labels[0]);
                }
            }
        env:
          VERSION: ${{ steps.version.outputs.version }}

      - name: Add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ${{ steps.get_label.outputs.label }}
